In [77]:
import numpy as np
import matplotlib.pyplot as plt

def derivative(a,b,n):
    dx = (b-a)/(n-1)
    D=(1/2)*(np.eye(n+1,n+1,1)-np.eye(n+1,n+1,-1))
    D[0][0] = -1
    D[-1][-1] = 1
    D[0][1] = 1
    D[-1][-2] = -1
    D = D/(dx)
    return D

In [78]:
derivative(0,1,10)

array([[-9. ,  9. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [-4.5,  0. ,  4.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. , -4.5,  0. ,  4.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. , -4.5,  0. ,  4.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. , -4.5,  0. ,  4.5,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. , -4.5,  0. ,  4.5,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. , -4.5,  0. ,  4.5,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. , -4.5,  0. ,  4.5,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. , -4.5,  0. ,  4.5,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. , -4.5,  0. ,  4.5],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. , -9. ,  9. ]])

In [82]:
D2 = np.eye(4,4,1)

In [83]:
D2

array([[ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.]])

In [84]:
D2[0][0]=2
D2[0][1]=-4
D2[0][2]=2

In [85]:
D2

array([[ 2., -4.,  2.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.]])

In [86]:
D2[1][0]=2
D2[1][1]=-3
D2[1][3]=1

In [87]:
D2

array([[ 2., -4.,  2.,  0.],
       [ 2., -3.,  1.,  1.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.]])

In [88]:
D2[-1][-1]=2
D2[-1][-2]=-4
D2[-1][-3]=2

In [89]:
D2

array([[ 2., -4.,  2.,  0.],
       [ 2., -3.,  1.,  1.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  2., -4.,  2.]])

In [90]:
D2[-2][-1]=2
D2[-2][-2]=-3
D2[-2][-3]=-1

In [91]:
D2

array([[ 2., -4.,  2.,  0.],
       [ 2., -3.,  1.,  1.],
       [ 0., -1., -3.,  2.],
       [ 0.,  2., -4.,  2.]])